### ISSUE TITLE
Liquid STX Token Design

### ISSUE THREAD

**Issue by will-corcoran** [stacksgov/critical-bounties#15]
### Discussed in https://github.com/stacksgov/Stacks-Grant-Launchpad/discussions/910

<div type='discussions-op-text'>

### **Introduction:**

We are excited to announce our latest batch of Critical Bounties (RFP-style grants)! With a total funding up for grabs of 12 BTC and 250k STX, we are seeking talented individuals to help us drive the sBTC, Bitcoin on Stacks, Stacks, and Clarity forward. Applications will be open from 5.12.23 to 6.20.23. Don't miss this chance to be a part of the future of Bitcoin L2 and Stacks!

### **Critical Bounty Mission Statement:**

The mission of this Critical Bounty is to develop a comprehensive liquid stacking module for STX on Stacks that increases liquidity and participation in the network. With the introduction of liquid STX and sBTC, we aim to provide a streamlined stacking process for users and offer rewards for securing the network while maintaining liquidity. Our module will include pooled funds, modularized stacking strategies, automated reward conversion, stSTX token issuance, and liquid stacking features. Join us in creating a more accessible and secure Stacks ecosystem.

### **Functionality / Deliverables (shall include, but not be limited to):**

- Design and develop a comprehensive liquid stacking protocol that streamlines the stacking process for STX.
- Implement pooled funds to allow users to collectively participate in stacking, leveraging economies of scale, and increasing rewards for all participants.
- Utilize a modular stacking strategy to optimally allocate pooled STX tokens for stacking, manage the stacking process, and incorporate rebalancing and optimization logic for enhanced liquid stacking performance.
- Automate the conversion of accrued BTC rewards to sBTC, providing a more accessible and liquid form of rewards for users.
- Issue stSTX tokens to users, representing their stacked assets and rewards, allowing them to track their investment and accrued earnings.
- Enable users to trade, sell, or utilize their stSTX tokens on other DeFi platforms while continuing to accrue rewards from stacking, increasing liquidity and flexibility within the Stacks ecosystem.

### **Required Knowledge / Skills:**

- Proficient in Clarity/Clarinet, Typescript/Unit Testing, React and Stacks.js or Micro-Stacks.
- Knowledgeable in DeFi concepts such as liquidity pools, yield farming, and automated market makers (AMMs).
- Understand cryptography, token economics, including token distribution, inflation, and stacking rewards.
- Knowledgeable in Stacks PoX mechanism and Bitcoin.

### **References:**
[stx-future Design Document](https://github.com/jcnelson/stx-future) by @jcnelson 

### **Critical Bounty Fee:**

- Maximum Fee: 100k STX</div>

### **APPLICATIONS ARE NOW CLOSED**

CHECK BACK FOR MORE CRITICAL BOUNTIES IN LATE-AUGUST

**Comment by stacks-foundation** [comment]
👋 @will-at-stacks
</br>
Thanks for your application!  We will do a pre-review and let you know if we have any immediate questions.  In the mean time please refer to our review schedule [here](https://github.com/stacksgov/Stacks-Grant-Launchpad/wiki/Grant-Process-and-Payments#application-review-phase-schedule) for a detailed timeline and response dates.
</br>
Best, 
Will

**Comment by efiko-dev** [comment]
Hi, just following up here since we applied and didnt hear back (yet). Be on the lookout for the application from Efiko, thanks!

**Comment by will-corcoran** [comment]
> Hi, just following up here since we applied and didnt hear back (yet). Be on the lookout for the application from Efiko, thanks!

Hi @efiko-dev thanks for reaching out.  Yes, your application was received.  We will provide an update a week or so after applications close on 6/20.  Best, Will

**Comment by flexfinRTP** [comment]
Will, we have re-submitted with updated visuals and diagrams. Please see the latest submission.

**Comment by will-corcoran** [comment]
### **UPDATE ON CRITICAL BOUNTY SELECTION:**

Please note that the applications are in review.  We are first, prioritizing the selection of the [sBTC Testing Team](https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/914).  Once that selection has been made we will begin final reviews for all other Critical Bounties.  Our goal is to announce the selected critical bounty recipients the week of **July 10th**.

Best,
Will

( cc: @jennymith @igorsyl )

**Comment by will-corcoran** [comment]
Hi All -

We are excited to announce TWO recipients of the Liquid STX critical bounty!

Congrats to :
@philipdesmedt @proiacm 

The Arkadiko and Whitelabel teams have agreed to a reduced fee of $32.5k in STX for producing a whitepaper over three months with three community meetings during the process.  Decisions on how to proceed from there will be dependent on community feedback.

If you could like to review all of the applications go [here](https://docs.google.com/spreadsheets/d/1w3L-MMkYQC8nPSxFLS3e7N5blm891f4ewZ8tsZT4Mmg/edit#gid=1649999758). 

Thanks to all that applied!

Best,
Will

**Comment by philiphacks** [comment]
Thanks @will-at-stacks!

Looking forward to it :)

**Comment by proiacm** [comment]
Thank you @will-at-stacks!
