### ISSUE TITLE
STX Mining Statistics Dashboard & How-To Documentation

### ISSUE THREAD

**Issue by will-corcoran** [stacksgov/critical-bounties#21]
**Recipient:** Signal21
**Bounty:** $45,000

## Project Approach

Creating a new 'Stacks Mining' dashboard on Signal21 and documentation to help others mine STX.

## Deliverables

1. **Mining Metrics Dashboard**:
    - STX block height
    - BTC block height
    - BTC spent last 100 blocks
    - BTC spent all time
    - BTC spent per miner last 100 blocks
    - Blocks won per miner last 100 blocks
    - Profit metric per miner BTC spent to STX won
    - TX fees per block
    - Total BTC fees from miners
    - Current BTC hashrate
    - Active Miners
    - Block rewards totals
    - Total sats committed per block
    - Sats spent per block by miner
    - Block reward distribution by miner
    - Table of winning miners by block and sats spent
    - Stacking TVL
    - Stacking rewards in BTC
    - Stackers (paid)
    - APY of Stacking rewards per cycle

2. **Stacks Mining Wiki**: 
    - A comprehensive guide to help get more miners onboard.

## Roadmap & Timeline

- **Milestone 1**: Initial development of the 'Stacks Mining' dashboard (4 weeks).
- **Milestone 2**: Integration of mining metrics (6 weeks).
- **Milestone 3**: Development and integration of the Stacks Mining wiki (3 weeks).
- **Milestone 4**: Testing and refinement of dashboard features (2 weeks).
- **Milestone 5**: Final deployment and community feedback integration (2 weeks).

**Comment by will-corcoran** [comment]
Hi Jonathan - 

I hope you are well.  

Now that we are about a month into having awarded this Critical Bounty, we would kindly request that you provide an update here for the community.  Before the end of the week (Friday, August 16th) can you please provide us an update on the status of your Critical Bounty, please make sure to include:
- Summary of CB-related work that has been done to date
- Summary of CB roadmap from here to completion
- Flag an potential blockers
- Anticipated date of completion
- Link to all related repos (remember all funded work should be open source)

Thanks!
Will

cc: @shaktistacks

**Comment by signal21j** [comment]
Hi Will,

We are making great progress on the Stacks Mining Dashboard and Wiki! Here's an overview of the progress of our Critical Bounty work:

Summary of CB-related work to date:
- We have successfully gathered all the necessary data for the dashboard.
- A working prototype of the 'Stacks Mining' dashboard has been developed.
- We're currently focusing on improving the performance to ensure that users can easily query the mining data.
- So far, approximately 30% of the charts have been built and integrated.

Summary of CB roadmap from here to completion:
- Over the next 4 weeks, we will be finalizing the mining dashboard.
- By the end of this period, we plan to launch the initial dashboard on Signal21.
- The subsequent 4 weeks will focus on the development and integration of the Stacks Mining wiki.
- The final 2 weeks will be dedicated to feedback collection, refinement, and testing.

Potential Blockers:
- At this time, we are not encountering any blockers.

Anticipated Date of Completion:
- We anticipate completing the project by October 31, 2024.

Link to Repositories:
- We will be adding the SQL queries for the mining dashboard shortly, ensuring all work remains open source.

We’re excited to continue pushing forward with this project!

Best regards,  
Jonathan

**Comment by signal21j** [comment]
Here's a screenshot of the WIP dashboard!
![screencapture-app-signal21-io-dashboards-S21-Stacks-Critical-Bounty-Mining-Dashboard-368-2024-08-15-21_36_51](https://github.com/user-attachments/assets/a4af4171-09a7-4427-b041-f9d1d2e5dcb2)

**Comment by will-corcoran** [comment]
Hi @signal21j 

We're exploring allocating our remaining 2024 grants budget and considering follow-up funding for current Critical Bounty recipients. If you have ideas to enhance your previously awarded work, we'd like to hear from you.

### **Next Steps:**

1. If you're interested in follow-up funding, please let us know by the end of this week.
2. You can either:
  -   Post your proposal as a comment on this issue (preferred for final submissions)
  -   Email me your initial thoughts if you're still developing your idea or prefer privacy

### **Proposal Details:**

- Please include:
  - Additional scope or enhancements
  - Associated costs
  - Justification for how a follow-up grant could significantly boost the ROI of the initial grant

We look forward to your ideas!

Best,
Will

**Comment by signal21j** [comment]
Thanks Will. We'd love to enhance our project and will put our heads together and follow up shortly! Jon

**Comment by friedger** [comment]
About "Profit metric per miner BTC spent to STX won", that could be shown together with sats/stx price to see whether miners are profitable or not.

**Comment by signal21j** [comment]
The mining dashboard is 99% complete! We are double checking a few datapoints but otherwise looks good and will be ready to push live shortly.
![Stacks Mining Dashboard Oct 2024 Signal21](https://github.com/user-attachments/assets/4dcfa962-9503-4483-a6dd-71b8a40453b3)

**Comment by signal21j** [comment]
Hi Will and Stacks Community,

I’m excited to announce that the Stacks Mining Dashboard and Wiki are now live on Signal21! This completes the work for the Critical Bounty, and we’re thrilled to provide these tools to support the community's mining efforts. 

Thank you for the opportunity to contribute. We look forward to seeing how the community uses these resources!

Best,  

Jonathan & the Signal21 Team

Link to the dashboard: https://app.signal21.io/stacks/mining

**Comment by will-corcoran** [comment]
Awesome work @signal21j !  I will work with @shaktistacks to get your final payment processed and close this issue.

**Comment by will-corcoran** [comment]
Hey @signal21j I am going to share your GH user name with some core devs that are coming across some mining related items.  They are going to tag you in some issues to track so you can update your wiki accordingly.

**Comment by friedger** [comment]
The main challenge for miners is to decide the amount of btc to commit and the btc fees. The wiki could explain how to read the dashboard data and find answers to their challenges.
