### ISSUE TITLE
Bitcoin to Stacks Bridge (Runes & Ordinals)

### ISSUE THREAD

**Issue by will-corcoran** [stacksgov/critical-bounties#22]
**Recipient:** Asigna
**Bounty:** $80k

## Project Approach

Asigna bridge is based on multisig on Stacks and on Bitcoin (other networks will be added after the first launch). Multiple nodes from multiple trusted and solid projects on Stacks and Bitcoin will be set up to secure the bridging capabilities, therefore not a single project or entity will have too much control on user funds.

All source code will be presented asap to conduct internal audits and gather important feedback from all participants.

Main information about the bridging architecture:
- All source code is written in Node.js.
- Signer nodes have the full validation/verification logic to avoid potential issues with the main listener and could switch to the other one if that one acts maliciously. Transactions won’t be signed if at least one verification check is failing.
- Asigna collects a small fee to the treasury from bridging operations (fee is to be defined).
- In the first version, only Bitcoin and Stacks networks will be included in the bridging process, including Runes, Ordinals, BTC as pre-sBTC.
- In a rare case of an emergency situation like someone sends to the bridge multisig a huge amount of whatever unsupported asset or a migration to a new set of nodes is needed, there’s a manual transaction flow applied. Manual transaction is presented by the listener and could be signed only directly in the terminal by the signer node after manual verification of the transaction legitimacy. In this case, the listener will be stopped until this transaction goes through to avoid potential collisions.
- If a transaction is stuck in the target blockchain, it is possible to speed up the transaction and the listener will initiate the process after ~N blocks (different for each blockchain). Signer nodes verify and validate the gas amount applied, compare transactions to be exactly the same, and verify that the time passed is enough to apply the gas fee increase.
- Bridging from Stacks to Bitcoin and back is done in a single operation.
- Different metaprotocols from Bitcoin, standards on Stacks, other networks with any VMs can be supported by such a bridging solution since it does not rely on Smart contract proofs, but rather on a wide trusted set of node signers from multiple entities.

## Deliverables

- **Smart contracts**:
  - `asigna-bridge-controller.clar`: Allows migration of ownership to a new set of multisig signers.
  - `asigna-bridge-fee-manager.clar`: Allows configuration of bridging fees for v1.
  - `asigna-bridge-v1.clar`: Main bridging contract. ONLY bridge multisig set of signers can finalize BTC -> Stacks bridge operations.
  - `asigna-ordinals-nft.clar`: Ordinals wrapper.
  - `asigna-bridge-ft.clar`: Fungible wrapper for psBTC and Runes.

## Roadmap & Timeline

- **Milestone 1**: Initial setup and development of Node.js application for bridging operations (6 weeks).
- **Milestone 2**: Implementation of multisig signer nodes and validation/verification logic (8 weeks).
- **Milestone 3**: Development of smart contracts and integration with the Node.js application (10 weeks).
- **Milestone 4**: Testing and security audits, including internal audits and feedback gathering from participants (6 weeks).
- **Milestone 5**: Deployment and monitoring of the bridge operations, including emergency handling mechanisms (4 weeks).

**Comment by will-corcoran** [comment]
Hi @fess-v - 

I hope you are well.  

Now that we are about a month into having awarded this Critical Bounty, we would kindly request that you provide an update here for the community.  Before the end of the week (Friday, August 16th) can you please provide us an update on the status of your Critical Bounty, please make sure to include:
- Summary of CB-related work that has been done to date
- Summary of CB roadmap from here to completion
- Flag an potential blockers
- Anticipated date of completion
- Link to all related repos (remember all funded work should be open source)

Thanks!
Will

cc: @shaktistacks

**Comment by fess-v** [comment]
Hey guys! 
What was done already:
1. Backend is finished for STX and BTC signers
2. Smart contracts finished and audited by Clarity Alliance (minor fixes left which will be done by the end of the weekend)
3. The frontend part is done
4. The whole source code is shared between signer participants and we started gathering public keys for the bridge multisig
5. Signer participants gathered (12) almost to the maximum possible (15), we will add more signers within the next week
6. EVM smart contracts are done as well, the audit starts on Monday

The date of the bridge going live is estimated at the same time as the Nakamoto goes live.

@will-corcoran sent you an invitation to the bridge repos. While it is important to eventually make it open source, we should consider opening the bridge backend code only to a private group in the first release so we can avoid potential hacks when the bridge goes live
And after the bridge is battle-tested in production we should open the rest code to public. 
Smart contract code can be open-sourced before release, just waiting on the final audit fixes at this point.

**Comment by will-corcoran** [comment]
Hi @fess-v 

We're exploring allocating our remaining 2024 grants budget and considering follow-up funding for current Critical Bounty recipients. If you have ideas to enhance your previously awarded work, we'd like to hear from you.

### **Next Steps:**

1. If you're interested in follow-up funding, please let us know by the end of this week.
2. You can either:
  -   Post your proposal as a comment on this issue (preferred for final submissions)
  -   Email me your initial thoughts if you're still developing your idea or prefer privacy

### **Proposal Details:**

- Please include:
  - Additional scope or enhancements
  - Associated costs
  - Justification for how a follow-up grant could significantly boost the ROI of the initial grant

We look forward to your ideas!

Best,
Will

**Comment by fess-v** [comment]
Hey @will-corcoran just dropped you a message by email, thanks a lot for pinging here!

**Comment by will-corcoran** [comment]
Hi @fess-v can you please provide an update on the status of the bridge project?

**Comment by fess-v** [comment]
Hi @will-corcoran! it is already live privately on mainnet, this week we're opening it to a wider list of private whitelisted addresses. We will be live publicly somewhere next week or the week after the next one!
