### ISSUE TITLE
Solo Stacking Solutions

### ISSUE THREAD

**Issue by will-corcoran** [stacksgov/critical-bounties#24]
Recipient: Degen Lab
Bounty: $24,300

## Project Approach

**Solo Stacker Functionalities:**

- **Independent Signer Infrastructure**: Can be deployed and run before starting Solo Stacker functionalities.
- **Operations**: Built on Signer Signatures infrastructure for exchanges, utilizing a signer key in the stacking process.
- **Frontend Integration**: Users stack solo via the frontend, with backend communication for signing parameters.
- **Server Setup**: Dedicated server running Bitcoin node, Stacks node, and signer for increased uptime and reduced timeouts.
- **Architecture**: Frontend for user interactions, backend for processing and generating signatures.
- **Key Functions**:
    - stack-stx
    - stack-aggregation-commit
    - stack-extend
    - stack-increase
    - stack-aggregation-increase
- **Parameters**: Validations on frontend and backend for reward cycle, Bitcoin address, max amount, auth id, duration, and signer key.
- **Backend API**: Can generate signatures for multiple contract calls, supporting separation of solo stacking and exchanges.

## Deliverables

- **Deliverable 1: Functional Solo Stacking**
    - Develop frontend and backend infrastructure.
    - Implement `stack-stx` operation with user-friendly inputs and validations.
    - Create backend requests and responses for signature generation.
    - Integrate wallet connect for auto-determining user’s STX and BTC addresses.
    - Build a template for other solo-stacking operations.
- **Deliverable 2: Solo Stacking Testing**
    - Conduct manual end-to-end testing on devnet/nakamoto testnet.
    - Test connected and unconnected states for `stack-stx`, `stack-increase`, and `stack-extend`.
    - Validate user inputs and ensure explicit data type conversions.
    - Optimize backend operations and explore migrating certain functions to the frontend.
- **Deliverable 3: Front End Enhanced Experience, Mobile Optimization, and Platform Hosting**
    - Improve UI/UX with third-party frameworks, tooltips, and inline help messages.
    - Ensure responsive design for mobile devices.
    - Host platform online, deploy new server, nodes, and signer.
    - Implement network security measures against DDoS attacks.

## Roadmap & Timeline

- **Milestone 1**: Initial setup and development of independent signer infrastructure (4 weeks).
- **Milestone 2**: Development of frontend and backend for `stack-stx` operation (6 weeks).
- **Milestone 3**: Implementation and integration of additional solo-stacking operations (8 weeks).
- **Milestone 4**: Comprehensive testing on devnet/nakamoto testnet and optimization (4 weeks).
- **Milestone 5**: Frontend enhancements, mobile optimization, and deployment of the platform (6 weeks).

**Comment by BowTiedSirJonathan** [comment]
### Update on Solo Stacking Progress

**Deliverable 1 - Functional Front End and Backend Solo Stacking Operations: completed**

- Sprint 1 - Develop a front-end with `stack-stx` function implemented [here](https://github.com/degen-lab/solo-stacking-old/commit/9ff3d932c79887314c55f9b58ce309f6858a1dc3)
- Sprint 2 - Implement `stack-extend` and `stack-increase` functionalities above the existing application [here](https://github.com/degen-lab/solo-stacking-old/commit/9ff3d932c79887314c55f9b58ce309f6858a1dc3)

**Deliverable 2 - Flow testings & limitations: completed**
- Sprint 3 - Perform manual end to end testing using devnet/nakamoto testnet to ensure all operations perform as expected [here](https://github.com/degen-lab/solo-stacking/blob/main/test.md)

**Comment by BowTiedSirJonathan** [comment]
### Update on Solo Stacking Progress - Completed
**Deliverable 3 -  Front End Enhanced Experience, Mobile Optimization, and Platform Hosting : completed**

### Is live on [solo.stacking.tools](https://solo.stacking.tools/)
### [github repository](https://github.com/degen-lab/solo-stacking)

@will-corcoran @shaktistacks

**Comment by diwakergupta** [comment]
> ### Update on Solo Stacking Progress - Completed
> **Deliverable 3 - Front End Enhanced Experience, Mobile Optimization, and Platform Hosting : completed**
> 
> ### Is live on [solo.stacking.tools](https://solo.stacking.tools/)
> ### [github repository](https://github.com/degen-lab/solo-stacking)

Exciting! Is the GH repo meant to be public? I think it's private now (404s for me).

I'm also curious how this compares to lockstacks.com?

**Comment by BowTiedSirJonathan** [comment]
Hello @diwakergupta! The repo is public now, thank you for mentioning it.

The main difference is that the end users that stack don’t need to run their signer as this is using the signer backend infrastructure we’ve built for generating signatures. 

https://signature.stacking.tools/

**Comment by will-corcoran** [comment]
This is great!  Thanks so much @BowTiedSirJonathan !  I will work with @shaktistacks to get the remainder of the bounty paid out to you.

**Comment by will-corcoran** [comment]
Hi @BowTiedSirJonathan 

We're exploring allocating our remaining 2024 grants budget and considering follow-up funding for current Critical Bounty recipients. If you have ideas to enhance your previously awarded work, we'd like to hear from you.

### **Next Steps:**

1. If you're interested in follow-up funding, please let us know by the end of this week.
2. You can either:
  -   Post your proposal as a comment on this issue (preferred for final submissions)
  -   Email me your initial thoughts if you're still developing your idea or prefer privacy

### **Proposal Details:**

- Please include:
  - Additional scope or enhancements
  - Associated costs
  - Justification for how a follow-up grant could significantly boost the ROI of the initial grant

We look forward to your ideas!

Best,
Will

**Comment by BowTiedSirJonathan** [comment]
Hi @will-corcoran 

Happy to hear this! 

Please find attached the justification for the follow up grant and the plan for it alongside the associated costs. 
- [justification document](https://www.notion.so/degenlab/Enhancing-Ecosystem-ROI-Through-Strategic-Grant-Expansion-5fd940f3a6cb4f30bdecf9d489e97339)
- [plan & costs document](https://www.notion.so/degenlab/Mining-Optimization-Platform-Automation-Simulation-and-Profit-Maximization-Tools-540cfe49e38c4a92a3c24175c40da131)

Best,
@BowTiedSirJonathan
