### ISSUE TITLE
Fast Paxos BFT Research & Implementation for WSTS

### ISSUE THREAD

**Issue by will-corcoran** [stacksgov/critical-bounties#25]
**Recipient:** Distributed Labs
**Bounty:** $20,000

### Summary

- **Problem**: Stackers need to collectively sign the block for appending to the Stacks blockchain.
    - **Options**:
        - **List of Single Signatures**:
            - No centralized coordination mechanism needed.
            - Extremely inefficient in size and verification cost.
        - **Threshold Signature (WSTS)**:
            - Fixed and small size and verification cost.
            - Scalable for thousands of participants.
            - Requires a coordination mechanism; vulnerable if the coordinator is dishonest or unavailable.
- **Proposed Solution**:
    - Conduct thorough research and analysis to decide which Fast Paxos BFT (Byzantine Fault Tolerance) paper to implement.
    - Ensure the chosen solution is rational, efficient, and secure.

## Deliverables

- **1st Phase Deliverables**:
    - Comprehensive analysis and due diligence report on various Fast Paxos BFT techniques.
        - Comparison of existing Fast Paxos BFT papers.
        - Evaluation of their feasibility, efficiency, and security for staker signatures.
    - Recommendation report outlining the best Fast Paxos BFT technique to implement.

## Roadmap & Timeline

- **Phase 1**: Research and analysis (6 weeks).
    - Conduct a detailed study of Fast Paxos BFT papers.
    - Produce a comprehensive analysis and due diligence report comparing the techniques.
    - Deliver a recommendation report on the best Fast Paxos BFT technique for implementation.
- **Phase 2**: Development planning (4 weeks).
    - Create a detailed development plan based on the chosen Fast Paxos BFT technique.
    - Outline the timeline and budget estimates for implementation.
- **Phase 3**: Implementation (12 weeks).
    - Develop the selected Fast Paxos BFT approach into an open-source RUST library.
    - Initial testing and iterations based on feedback.

**Comment by will-corcoran** [comment]
Hi @Alex-distributed-lab - 

I hope you are well.  

Now that we are about a month into having awarded this Critical Bounty, we would kindly request that you provide an update here for the community.  Before the end of the week (Friday, August 16th) can you please provide us an update on the status of your Critical Bounty, please make sure to include:
- Summary of CB-related work that has been done to date
- Summary of CB roadmap from here to completion
- Flag an potential blockers
- Anticipated date of completion
- Link to all related repos (remember all funded work should be open source)

Thanks!
Will

cc: @shaktistacks

**Comment by Alex-distributed-lab** [comment]
Hi @will-corcoran!

We successfully completed the first and second phases and are currently working on library implementation. A summary is below.

### Phase 1

1. We researched existing BFT Paxos protocols and wrote a paper describing all of them (including pros and cons, algorithms, and comparison). I have attached the paper here [BFT_Paxos_comp.pdf](https://github.com/user-attachments/files/16597513/BFT_Paxos_comp.pdf)
2. The BPCon version can be the best solution from a performance and clarity perspective. So, the decision to implement this version was made. Here, we prepared the document that describes how this protocol should work for Stacks:
[Paxos_for_Stacks.pdf](https://github.com/user-attachments/files/16597514/Paxos_for_Stacks.pdf)

### Phase 2

1. We discussed milestones and roadmap, and the development plan was the following:
    - **M1**: Interfaces definition and library skeleton ~1W
    - **M2**: Implementing ballot protocol ~1W
    - **M3**: Implementing configuration for ballots (e.g., timeslots, ballot leader selection, etc.) ~2W
    - **M4**: Tests and documentation ~1.5-2W
2. While developing the library, we found out that the plan should be updated by dedicating more time to **M2** and less to **M3**. It doesn't affect the timeline for the whole library.

### Phase 3

You can find the project repository here: https://github.com/distributed-lab/bpcon.

1. We started development on July 22nd, and the M1 is finished now https://github.com/distributed-lab/bpcon/issues/1
2. M2 is also ready and is under review. Corresponding PR you can find here: https://github.com/distributed-lab/bpcon/pull/6
3. M3 and M4 are on track and should be done by the end of August 2024.

We have no blockers and move within the planned roadmap. Feel free to let me know if you have any questions.

Thank you!

**Comment by will-corcoran** [comment]
Hi @Alex-distributed-lab 

 We're exploring allocating our remaining 2024 grants budget and considering follow-up funding for current Critical Bounty recipients. If you have ideas to enhance your previously awarded work, we'd like to hear from you.

### **Next Steps:**

1. If you're interested in follow-up funding, please let us know by the end of this week.
2. You can either:
  -   Post your proposal as a comment on this issue (preferred for final submissions)
  -   Email me your initial thoughts if you're still developing your idea or prefer privacy

### **Proposal Details:**

- Please include:
  - Additional scope or enhancements
  - Associated costs
  - Justification for how a follow-up grant could significantly boost the ROI of the initial grant

We look forward to your ideas!

Best,
Will

**Comment by Alex-distributed-lab** [comment]
Hi @will-corcoran!

First of all, let me provide an update on the current state. Then, we will think about what the next proposal could be. 

So, we have completed all the phases described above, and all PR was successfully accepted and merged (including tests and documentation). Special thanks to @cylewitruk for the review!

You can find the codebase here: https://github.com/distributed-lab/bpcon.  

Additionally, we agreed if some support is needed from our side while integrating it into the Nakamoto upgrade, we will definitely provide it (planned by the end of September).

Thanks for your kind support!
