### ISSUE TITLE
Development and Maintenance of Real-Time Stacks DeFi Analytics Dashboard

### ISSUE THREAD

**Issue by will-corcoran** [stacksgov/critical-bounties#29]
**Recipient:** Leopadel
**Bounty:** $5,600

## Project Approach

This project aims to provide a real-time view of the Stacks DeFi ecosystem by aggregating public blockchain data and making it accessible through an easy-to-use interface.

**Project Proposal**:

- **Project**: Development and 6-month maintenance of [stackspulse.com](http://stackspulse.com/).
- **Website**: Live, open-source, provides real-time view of Stacks DeFi ecosystem.
- **Features**:
    - Aggregates public blockchain data.
    - Easy-to-use interface.
    - Highlights most used protocols and traded memecoins.
    - Engages community via Twitter with daily/weekly stats.
- **Community Engagement**:
    - 500+ followers.
    - 2k+ unique visitors.

## Deliverables

1. **Deploy Stacks Node**: Complete deployment of the Stacks node to support data aggregation.
2. **Migrate stackspulse to Stacks Postgres DB**: Transition the backend database to Postgres for improved performance and scalability.
3. **Add Lisa Protocol**: Integrate the Lisa Protocol into the platform.
4. **Daily Protocol Tweets**: Automate daily tweets highlighting protocol activities and stats.
5. **Memecoin Stats Focus**:
    - Create a specific memecoin activity page.
    - Post daily/weekly memecoin stats on Twitter.
6. **Post-Nakamoto Update**: Ensure smooth operation post-Nakamoto update and update dependencies as needed.

## Roadmap & Timeline

- **Milestone 1**: Deploy Stacks Node (1 day)
    - Set up and configure the Stacks node.
- **Milestone 2**: Migrate stackspulse to Stacks Postgres DB (1 day)
    - Complete migration to the Postgres database.
- **Milestone 3**: Add Lisa Protocol (0.5 day)
    - Integrate and test the Lisa Protocol.
- **Milestone 4**: Daily Protocol Tweets (2 hours)
    - Automate daily protocol activity tweets.
- **Milestone 5**: Memecoin Stats Focus (1 week)
    - Develop a dedicated memecoin activity page.
    - Post daily/weekly memecoin stats on Twitter.
- **Milestone 6**: Post-Nakamoto Update (1 day)
    - Ensure all systems are updated and operating smoothly post-Nakamoto update.

**Comment by will-corcoran** [comment]
Hi @pradel - 

I hope you are well.  Now that we are about a month into having awarded this Critical Bounty, we would kindly request that you provide an update here for the community.  Before the end of the week (Friday, August 16th) can you please provide us an update on the status of your Critical Bounty, please make sure to include:
- Summary of CB-related work that has been done to date
- Summary of CB roadmap from here to completion
- Flag an potential blockers
- Anticipated date of completion
- Link to all related repos (remember all funded work should be open source)

Thanks!
Will

cc: @shaktistacks

**Comment by pradel** [comment]
Hey Will, 

Current status is the following:

- Milestone 1: The Stacks node is deployed and the ansible and docs to deploy a node can be found here https://github.com/pradel/stackspulse/tree/main/ansible
- Milestone 2: it was overly underestimated in time and took around 1+ weeks to complete (had to do a major refactor of the code). The SQL queries are quite slow so I had to implement a caching mechanism around them to ensure we always have some data. I still want to improve the queries and am exploring solutions to make the stats run faster.
- Milestone 3: Done, the dashboard can be seen here https://www.stackspulse.com/protocols/lisa

On top of the following tasks 2 other protocols (not part of the grant) have been added as requested by the community:
- Zest https://www.stackspulse.com/protocols/zest
- Charisma https://www.stackspulse.com/protocols/charisma

No blockers are expected so far.
The completion date for the improvements and remaining tasks is estimated at the beginning of October.

Links:
- Code of the repository https://github.com/pradel/stackspulse

**Comment by will-corcoran** [comment]
Hi @pradel 

 We're exploring allocating our remaining 2024 grants budget and considering follow-up funding for current Critical Bounty recipients. If you have ideas to enhance your previously awarded work, we'd like to hear from you.

### **Next Steps:**

1. If you're interested in follow-up funding, please let us know by the end of this week.
2. You can either:
  -   Post your proposal as a comment on this issue (preferred for final submissions)
  -   Email me your initial thoughts if you're still developing your idea or prefer privacy

### **Proposal Details:**

- Please include:
  - Additional scope or enhancements
  - Associated costs
  - Justification for how a follow-up grant could significantly boost the ROI of the initial grant

We look forward to your ideas!

Best,
Will

**Comment by pradel** [comment]
@will-corcoran update:

- Milstone 5: in progress. The goal of this milestone was to focus on memecoin stats, but I decided to make it a more generic approach that works for all tokens (not just memecoin) so you can see stats for aeUSDC etc.. I already have the individual page showing the supply, holders, transaction volume and holders table to show the token distribution and activity. Example for [WELSH](https://www.stackspulse.com/tokens/SP3NE50GEXFG9SZGTT51P40X2CKYSZ5CC4ZTZ7A2G.welshcorgicoin-token::welshcorgicoin). I need to rething the navigation of the website to make it easy to find the tokens you are looking for. I expect to be done with the milestone in 2/3 weeks.

- Milestone 6: Waiting for Nakamoto to go live, but I already upgraded the code to work with the latest stacks-blockchain-api v8.x in https://github.com/pradel/stackspulse/pull/129 and https://github.com/pradel/stackspulse/pull/127 so the upgrade post nakamoto should be relatively fast.

**Comment by pradel** [comment]
@will-corcoran update:

- Milestone 5: Done. You can see the newly created pages live here [tokens list](https://www.stackspulse.com/tokens) [WELSH page](https://www.stackspulse.com/tokens/SP3NE50GEXFG9SZGTT51P40X2CKYSZ5CC4ZTZ7A2G.welshcorgicoin-token).

- Milestone 6: Waiting for Nakamoto to go live to finish the upgrade.

After talking with some Defi protocols, it appears that nested contract calls are not counted for the protocol. Eg: using Bitflow aggregator with a Velar pool will only count a unique user for Bitflow but not Velar. This is something I am working to fix at the moment to get correct stats.

**Comment by pradel** [comment]
@will-corcoran update:

- we are now tracking correctly calls made from nested contracts

- Milestone 6: the node has been updated to 3.0.0.0.0 so it's ready for nakamoto 🔥 

With these updates, I am now done with the work for the grant. Will keep monitoring after nakamoto is live but everything is ready on my side!

**Comment by will-corcoran** [comment]
Hi @pradel thanks for the update!  Sorry I am just now seeing this.  I will work with @shaktistacks to get your final payment processed.  The site is looking 🔥 !

I will close this issue now to signal the CB as complete
